#!/bin/sh

# Power menu script using rofi

CHOSEN=$(printf "Lock\nReboot\nShutdown\nSuspend" | rofi -dmenu -i -p "Power Menu")

case "$CHOSEN" in
	"Lock") /home/jpatrick5402/.dotfiles/scripts/lock.sh ;;
	"Reboot") reboot ;;
	"Shutdown") poweroff ;;
	"Suspend") systemctl suspend-then-hibernate ;;
	*) exit 1 ;;
esac
